---
title: "Transfer Policy"
author: "Steicy Lopez"
output: pdf_document
---
```{r, echo=FALSE}
library(fixest)
library(MatchIt)
library(DRDID)
#___________________________________________________________ Loading in separate school years 
#_____________________ Creating loop for 1998 to 2019 (Other years had no transfer data)
start_year <- 1998
end_year <- 2019

for (year in start_year:end_year) {
  # Construct the file name and variable name
  filename <- paste0("MERGED", year, "_", substr(year + 1, 3, 4), "_PP.csv")
  var_name <- paste0("data", year)
  
  # Read the data
  data <- read.csv(filename)
  
  # Remove observations missing/errors COMP_4YR_TRANS_YR2_RT
  data <- data[!is.na(data$COMP_4YR_TRANS_YR2_RT), ]

  data<- data[data$COMP_4YR_TRANS_YR2_RT != "PS", ] 

  # Remove observations whose predominate and highest degree arent associates degree
  data <- data[data$PREDDEG == 2 & data$HIGHDEG == 2, ]

  # Keeping only public institutions
  data <- data[data$CONTROL == 1, ]
  
  # Assign the filtered data to a variable
  assign(var_name, data)
}

rm(data) # removing placehold dataframe

#___________________________________________________________ Adding column to each set for the source year
data_frames <- ls(pattern = "^data\\d{4}$") # Grabbing names of data frames

for (df_name in data_frames) {
  # grabbing the 5th and 6th digits (year)
  year_digits <- substr(df_name, 5, 8) 

  # grabbing the file name
  df <- get(df_name)

  # creating the column with the last two digits
  df$year_source <- year_digits 

  # actually saving into the data frame
  assign(df_name, df) 
}

rm(df) # removing placehold dataframe

#___________________________________________________________ Making a MEGA data set
mega_data <- rbind(data1998, data1999, data2000, data2001, data2002, data2003, data2004, data2005, data2006, data2007, data2008, data2009, data2010, data2011, data2012, data2013, data2014, data2015, data2016, data2017, data2018, data2019)

write.csv(mega_data, "mega_data.csv") #saving the file as csv

```

```{r, echo=FALSE, warning=FALSE}
# Loading packages
library(tidyverse)
library(fixest)
library(MatchIt)
library(DRDID)
library(did)
library(dplyr)
library(psych)
library(ggplot2)

# Loading data in 
mega_data <-read_csv("mega_data.csv") # college scorecard data, after merge and drop of missing dependent var 

years_treat <- read_csv("College_transfer_years.csv") # data with Di or treated variable and year of treatment

# Merging acoording to state acronym

  ## First rename var to match mega_data 
  mega_data <- rename(mega_data, "state" = "STABBR")

  ## Merge
  df <- merge(mega_data, years_treat, by = "state", all.x = TRUE)

  ##Formatting fixes
  df <- rename(df, "yi" = "COMP_4YR_TRANS_YR2_RT")

  df$yi <- as.numeric(df$yi)
  df$year_source <- as.numeric(df$year_source)
  df$treated_year<- as.numeric(df$treated_year)

```

```{r, echo=FALSE, warning=FALSE}
# Graphing 
  df$di <- as.factor(df$di)

  df$treated <- as.factor(df$treated)

treated <- filter(df, di==1)
control <- filter(df, (treated ==0 & di == 0) )

boxplot(yi ~ year_source, data = treated,
        main = "Treated States",
        xlab = "Year",
        ylab = "Transfer Completion Rate")
```

```{r, echo=FALSE, warning=FALSE}
#Prep for data analysis 
df$treated_year[is.na(df$treated_year)] <- 0

# Prepping
pre_processed_data <- pre_process_did(
  yname = "yi",             # Outcome variable
  tname = "year_source",     # Time variable
  gname = "treated_year",    # Group variable (first treatment period)
  idname = "ST_FIPS",         # Unique identifier
  data = df,
  allow_unbalanced_panel = TRUE,
  panel = TRUE,
  base_period = "universal", 
  control_group = "notyettreated", 
  xformla = ~ 1
)

processed_data_df <- pre_processed_data$data

att_results <- att_gt(
  yname = "yi",             # Outcome variable
  gname = "treated_year",    # Group variable (first treatment period)
  idname = "ST_FIPS",         # Unique identifier
  tname = "year_source",     # Time variable
  data = processed_data_df,  # Use preprocessed data
  allow_unbalanced_panel = TRUE, 
  base_period = "universal", 
  control_group = "notyettreated", 
  xformla = ~ 1
)
dynamic_att_results <- aggte(att_results, type = "dynamic", na.rm = TRUE)
ggdid(dynamic_att_results)


```

```{r}
# Prepping
pre_processed_data <- pre_process_did(
  yname = "yi",             # Outcome variable
  tname = "year_source",     # Time variable
  gname = "treated_year",    # Group variable (first treatment period)
  idname = "ST_FIPS",         # Unique identifier
  data = df,
  allow_unbalanced_panel = TRUE,
  panel = TRUE,
  base_period = "universal", 
  xformla = NULL
)

processed_data_df <- pre_processed_data$data

att_results <- att_gt(
  yname = "yi",             # Outcome variable
  gname = "treated_year",    # Group variable (first treatment period)
  idname = "ST_FIPS",         # Unique identifier
  tname = "year_source",      # Time variable
  base_period = "universal", 
  data = processed_data_df,  # Use preprocessed data
  allow_unbalanced_panel = TRUE,
  xformla = NULL
)
dynamic_att_results <- aggte(att_results, type = "dynamic", na.rm = TRUE)
ggdid(dynamic_att_results)

```

```{r}
df <- filter(df, year_source > 2004 & year_source < 2018)
# Prepping
pre_processed_data <- pre_process_did(
  yname = "yi",             # Outcome variable
  tname = "year_source",     # Time variable
  gname = "treated_year",    # Group variable (first treatment period)
  idname = "ST_FIPS",         # Unique identifier
  data = df,
  allow_unbalanced_panel = TRUE,
  panel = TRUE,
  base_period = "universal", 
  control = "notyettreated",
  xformla = ~ NULL
)

processed_data_df <- pre_processed_data$data

att_results <- att_gt(
  yname = "yi",             # Outcome variable
  gname = "treated_year",    # Group variable (first treatment period)
  idname = "ST_FIPS",         # Unique identifier
  tname = "year_source",     # Time variable
  data = processed_data_df,  # Use preprocessed data
  allow_unbalanced_panel = TRUE, 
  base_period = "universal", 
  control_group = "notyettreated",
  xformla = ~ NULL
)
dynamic_att_results <- aggte(att_results, type = "dynamic", na.rm = TRUE)
ggdid(dynamic_att_results)

```